version: '3'
services:
  database:
    image: postgres
    container_name: postgres-blog
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    ports:
      - 5432:5432
    networks:
      - blog-network
  app:
    container_name: blog-api
    build:
      context: .
      dockerfile: dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
